### ISSUE TITLE
#ISSUE 1: Introducción

### ISSUE THREAD

**Issue by Ezmant** [Ezmant/Proyecto_FullStack_ISPC#2]

**Comment by RiotechFull** [comment]
A que hace referencia ? utilicen la seccion de comentarios para especificar que trabajan

**Comment by Ezmant** [comment]
Hola profe, todas las issues con este tipo de nombre "#ISSUE" hacen referencia a secciones del documento ieee del cual nos fuimos dividiendo los puntos, en este caso es la introducción del doc IEEE, como no tienen relacion con las US le pusimos esta nomenclatura para organizarnos un poco mejor.
