### ISSUE TITLE
#TK02 Buscar/crear diseño/template para el sitio web

### ISSUE THREAD

**Issue by Ezmant** [Ezmant/Proyecto_FullStack_ISPC#23]

**Comment by Ezmant** [comment]
Cada integrante del equipo busca un template.

**Comment by MelanieR24** [comment]
yo aporto este template: https://nicepage.com/es/st/159588/todo-sobre-perros-plantilla-web

**Comment by AmatoJazmin** [comment]
Aporto el siguiente template:
Descargar en https://www.free-css.com/free-css-templates/page280/petology
Vista previa en https://www.free-css.com/assets/files/free-css-templates/preview/page280/petology/

**Comment by Ezmant** [comment]
Aporto este [https://www.joomshaper.com//page-builder/layouts/pet-care](https://www.joomshaper.com//page-builder/layouts/pet-care)
